var searchData=
[
  ['vertex_0',['Vertex',['../struct_spices_1_1_vertex.html',1,'Spices::Vertex'],['../struct_spices_1_1_vertex.html#ad657bbe370bf162290f3b3780fca0164',1,'Spices::Vertex::Vertex()']]],
  ['vertex_2ecpp_1',['Vertex.cpp',['../_vertex_8cpp.html',1,'']]],
  ['vertex_2eh_2',['Vertex.h',['../_vertex_8h.html',1,'']]],
  ['viewport_3',['viewport',['../struct_spices_1_1_pipeline_config_info.html#a13c8d902b161e112c601cf44cd6ee49e',1,'Spices::PipelineConfigInfo']]],
  ['viewportinfo_4',['viewportInfo',['../struct_spices_1_1_pipeline_config_info.html#a3db482d5bfd1c7fa273a067a9009847f',1,'Spices::PipelineConfigInfo']]],
  ['viewportresizequeryer_5',['ViewPortResizeQueryer',['../class_spices_1_1_view_port_resize_queryer.html',1,'Spices']]],
  ['viewportsize_6',['viewPortSize',['../struct_spices_1_1_swap_chain_support_details.html#af7be824f7b9b8e12562323e57b001e9b',1,'Spices::SwapChainSupportDetails']]],
  ['vk_5fcheck_7',['VK_CHECK',['../_core_8h.html#a85a23631965b57ebf6e3e7fad1a15888',1,'Core.h']]],
  ['vulkanbuffer_8',['VulkanBuffer',['../class_spices_1_1_vulkan_buffer.html',1,'Spices::VulkanBuffer'],['../class_spices_1_1_vulkan_buffer.html#ace05f62d6d439787bc1204ec7b78c577',1,'Spices::VulkanBuffer::VulkanBuffer(VulkanState &amp;vulkanState)'],['../class_spices_1_1_vulkan_buffer.html#a018d60323350315137c18e80509184b5',1,'Spices::VulkanBuffer::VulkanBuffer(VulkanState &amp;vulkanState, VkDeviceSize size, VkBufferUsageFlags usage, VkMemoryPropertyFlags properties)']]],
  ['vulkanbuffer_2ecpp_9',['VulkanBuffer.cpp',['../_vulkan_buffer_8cpp.html',1,'']]],
  ['vulkanbuffer_2eh_10',['VulkanBuffer.h',['../_vulkan_buffer_8h.html',1,'']]],
  ['vulkancommandbuffer_11',['VulkanCommandBuffer',['../class_spices_1_1_vulkan_command_buffer.html',1,'Spices::VulkanCommandBuffer'],['../class_spices_1_1_vulkan_command_buffer.html#a527a2ce9081d7decdbeacfc2bea3f5e1',1,'Spices::VulkanCommandBuffer::VulkanCommandBuffer()']]],
  ['vulkancommandbuffer_2ecpp_12',['VulkanCommandBuffer.cpp',['../_vulkan_command_buffer_8cpp.html',1,'']]],
  ['vulkancommandbuffer_2eh_13',['VulkanCommandBuffer.h',['../_vulkan_command_buffer_8h.html',1,'']]],
  ['vulkancommandpool_14',['VulkanCommandPool',['../class_spices_1_1_vulkan_command_pool.html',1,'Spices::VulkanCommandPool'],['../class_spices_1_1_vulkan_command_pool.html#a83884b2055e17ddec50208b18c375317',1,'Spices::VulkanCommandPool::VulkanCommandPool()']]],
  ['vulkandebugutils_15',['VulkanDebugUtils',['../class_spices_1_1_vulkan_debug_utils.html',1,'Spices']]],
  ['vulkandebugutils_2ecpp_16',['VulkanDebugUtils.cpp',['../_vulkan_debug_utils_8cpp.html',1,'']]],
  ['vulkandebugutils_2eh_17',['VulkanDebugUtils.h',['../_vulkan_debug_utils_8h.html',1,'']]],
  ['vulkandescriptor_2ecpp_18',['VulkanDescriptor.cpp',['../_vulkan_descriptor_8cpp.html',1,'']]],
  ['vulkandescriptor_2eh_19',['VulkanDescriptor.h',['../_vulkan_descriptor_8h.html',1,'']]],
  ['vulkandescriptorpool_20',['VulkanDescriptorPool',['../class_spices_1_1_vulkan_descriptor_pool.html',1,'Spices::VulkanDescriptorPool'],['../class_spices_1_1_vulkan_descriptor_pool.html#a5a09108525ce9a761bed34a1a88c1786',1,'Spices::VulkanDescriptorPool::VulkanDescriptorPool()']]],
  ['vulkandescriptorset_21',['VulkanDescriptorSet',['../class_spices_1_1_vulkan_descriptor_set.html',1,'Spices::VulkanDescriptorSet'],['../class_spices_1_1_vulkan_descriptor_set.html#a57a630f500b0f75b21f79291d0a2b26b',1,'Spices::VulkanDescriptorSet::VulkanDescriptorSet()']]],
  ['vulkandescriptorsetlayout_22',['VulkanDescriptorSetLayout',['../class_spices_1_1_vulkan_descriptor_set_layout.html',1,'Spices::VulkanDescriptorSetLayout'],['../class_spices_1_1_vulkan_descriptor_set_layout.html#a9d5e6247d9dd7c00838cbd31d4bbf7bb',1,'Spices::VulkanDescriptorSetLayout::VulkanDescriptorSetLayout()']]],
  ['vulkandevice_23',['VulkanDevice',['../class_spices_1_1_vulkan_device.html',1,'Spices::VulkanDevice'],['../class_spices_1_1_vulkan_device.html#ad8a71cec167c6355fa221b99d8b6453f',1,'Spices::VulkanDevice::VulkanDevice()']]],
  ['vulkandevice_2ecpp_24',['VulkanDevice.cpp',['../_vulkan_device_8cpp.html',1,'']]],
  ['vulkandevice_2eh_25',['VulkanDevice.h',['../_vulkan_device_8h.html',1,'']]],
  ['vulkanimage_26',['VulkanImage',['../class_spices_1_1_vulkan_image.html',1,'Spices::VulkanImage'],['../class_spices_1_1_vulkan_image.html#ae5cff6a4a40cb84459a86843c8c59d2f',1,'Spices::VulkanImage::VulkanImage(VulkanState &amp;vulkanState)'],['../class_spices_1_1_vulkan_image.html#a8a08ce03d075acca58908ce35af0ecdc',1,'Spices::VulkanImage::VulkanImage(VulkanState &amp;vulkanState, const std::string &amp;name, VkImageType type, uint32_t width, uint32_t height, uint32_t layers, VkSampleCountFlagBits numSamples, VkFormat format, VkImageTiling tiling, VkImageUsageFlags usage, VkImageCreateFlags flags, VkMemoryPropertyFlags properties, uint32_t mipLevels)']]],
  ['vulkanimage_2ecpp_27',['VulkanImage.cpp',['../_vulkan_image_8cpp.html',1,'']]],
  ['vulkanimage_2eh_28',['VulkanImage.h',['../_vulkan_image_8h.html',1,'']]],
  ['vulkaninstance_29',['VulkanInstance',['../class_spices_1_1_vulkan_instance.html',1,'Spices::VulkanInstance'],['../class_spices_1_1_vulkan_instance.html#a883f633716d083d6902ca2188fd99765',1,'Spices::VulkanInstance::VulkanInstance()']]],
  ['vulkaninstance_2ecpp_30',['VulkanInstance.cpp',['../_vulkan_instance_8cpp.html',1,'']]],
  ['vulkaninstance_2eh_31',['VulkanInstance.h',['../_vulkan_instance_8h.html',1,'']]],
  ['vulkanobject_32',['VulkanObject',['../class_spices_1_1_vulkan_object.html',1,'Spices::VulkanObject'],['../class_spices_1_1_vulkan_object.html#ae235853074b4b926207b1980b25c9dee',1,'Spices::VulkanObject::VulkanObject(VulkanState &amp;vulkanState)'],['../class_spices_1_1_vulkan_object.html#a0c8fb641fba1238a8a097cc709d3f454',1,'Spices::VulkanObject::VulkanObject(const VulkanObject &amp;)=delete']]],
  ['vulkanpipeline_33',['VulkanPipeline',['../class_spices_1_1_vulkan_pipeline.html',1,'Spices::VulkanPipeline'],['../class_spices_1_1_vulkan_pipeline.html#a1484b08e67f3d1d06fc845780e84978d',1,'Spices::VulkanPipeline::VulkanPipeline(VulkanState &amp;vulkanState)'],['../class_spices_1_1_vulkan_pipeline.html#ab7e2f47a2a278fa025b48f1c324fe0d6',1,'Spices::VulkanPipeline::VulkanPipeline(VulkanState &amp;vulkanState, const std::string &amp;pipelineName, const std::unordered_map&lt; std::string, std::vector&lt; std::string &gt; &gt; &amp;shaders, const PipelineConfigInfo &amp;config)']]],
  ['vulkanpipeline_2ecpp_34',['VulkanPipeline.cpp',['../_vulkan_pipeline_8cpp.html',1,'']]],
  ['vulkanpipeline_2eh_35',['VulkanPipeline.h',['../_vulkan_pipeline_8h.html',1,'']]],
  ['vulkanraytracing_36',['VulkanRayTracing',['../class_spices_1_1_vulkan_ray_tracing.html',1,'Spices::VulkanRayTracing'],['../class_spices_1_1_vulkan_ray_tracing.html#a412ba256bbfc030f14dc140df9fc1362',1,'Spices::VulkanRayTracing::VulkanRayTracing()']]],
  ['vulkanraytracingpipeline_37',['VulkanRayTracingPipeline',['../class_spices_1_1_vulkan_ray_tracing_pipeline.html',1,'Spices::VulkanRayTracingPipeline'],['../class_spices_1_1_vulkan_ray_tracing_pipeline.html#af3eb2ffd7ed68fe3f71f6c717edfb606',1,'Spices::VulkanRayTracingPipeline::VulkanRayTracingPipeline()']]],
  ['vulkanrenderbackend_38',['VulkanRenderBackend',['../class_spices_1_1_vulkan_render_backend.html',1,'Spices::VulkanRenderBackend'],['../class_spices_1_1_vulkan_render_backend.html#a3f953a285812f4ca302c9eebf79bcdd7',1,'Spices::VulkanRenderBackend::VulkanRenderBackend()'],['../class_spices_1_1_vulkan_render_backend.html#aefabc7b7a5e38fc162b6b7a506e69b84',1,'Spices::VulkanRenderBackend::VulkanRenderBackend(const VulkanRenderBackend &amp;)=delete']]],
  ['vulkanrenderbackend_2ecpp_39',['VulkanRenderBackend.cpp',['../_vulkan_render_backend_8cpp.html',1,'']]],
  ['vulkanrenderbackend_2eh_40',['VulkanRenderBackend.h',['../_vulkan_render_backend_8h.html',1,'']]],
  ['vulkanrenderpass_41',['VulkanRenderPass',['../class_spices_1_1_vulkan_render_pass.html',1,'Spices::VulkanRenderPass'],['../class_spices_1_1_vulkan_render_pass.html#a154a62fa96d089c986facba8fe717f9b',1,'Spices::VulkanRenderPass::VulkanRenderPass()']]],
  ['vulkanrenderpass_2ecpp_42',['VulkanRenderPass.cpp',['../_vulkan_render_pass_8cpp.html',1,'']]],
  ['vulkanrenderpass_2eh_43',['VulkanRenderPass.h',['../_vulkan_render_pass_8h.html',1,'']]],
  ['vulkanshadermodule_44',['VulkanShaderModule',['../class_spices_1_1_vulkan_shader_module.html',1,'Spices::VulkanShaderModule'],['../class_spices_1_1_vulkan_shader_module.html#ab4018178128bea3c905d2b300e0ef2b9',1,'Spices::VulkanShaderModule::VulkanShaderModule()']]],
  ['vulkanshadermodule_2ecpp_45',['VulkanShaderModule.cpp',['../_vulkan_shader_module_8cpp.html',1,'']]],
  ['vulkanshadermodule_2eh_46',['VulkanShaderModule.h',['../_vulkan_shader_module_8h.html',1,'']]],
  ['vulkanstate_47',['VulkanState',['../struct_spices_1_1_vulkan_state.html',1,'Spices::VulkanState'],['../struct_spices_1_1_vulkan_state.html#a8766f4d1b6e25a29ffad310acd7712c8',1,'Spices::VulkanState::VulkanState()=default'],['../struct_spices_1_1_vulkan_state.html#a0f0c4ab610a72ef27845267053e8eb1b',1,'Spices::VulkanState::VulkanState(const VulkanState &amp;)=delete']]],
  ['vulkanswapchain_48',['VulkanSwapChain',['../class_spices_1_1_vulkan_swap_chain.html',1,'Spices::VulkanSwapChain'],['../class_spices_1_1_vulkan_swap_chain.html#a085802ae9f8f1544237a5183cb3022ac',1,'Spices::VulkanSwapChain::VulkanSwapChain()']]],
  ['vulkanswapchain_2ecpp_49',['VulkanSwapChain.cpp',['../_vulkan_swap_chain_8cpp.html',1,'']]],
  ['vulkanswapchain_2eh_50',['VulkanSwapChain.h',['../_vulkan_swap_chain_8h.html',1,'']]],
  ['vulkanutils_2eh_51',['VulkanUtils.h',['../_vulkan_utils_8h.html',1,'']]],
  ['vulkanwindows_52',['VulkanWindows',['../class_spices_1_1_vulkan_windows.html',1,'Spices::VulkanWindows'],['../class_spices_1_1_vulkan_windows.html#a1b2f9d0d621ddd9accb2ea8408de2e5c',1,'Spices::VulkanWindows::VulkanWindows()']]],
  ['vulkanwindows_2ecpp_53',['VulkanWindows.cpp',['../_vulkan_windows_8cpp.html',1,'']]],
  ['vulkanwindows_2eh_54',['VulkanWindows.h',['../_vulkan_windows_8h.html',1,'']]]
];
