var annotated_dup =
[
    [ "scl", null, [
      [ "linked_unordered_map", "classscl_1_1linked__unordered__map.html", "classscl_1_1linked__unordered__map" ],
      [ "runtime_memory_block", "classscl_1_1runtime__memory__block.html", "classscl_1_1runtime__memory__block" ]
    ] ],
    [ "Spices", null, [
      [ "RayTracingR", null, [
        [ "DirectionalLightBuffer", "struct_spices_1_1_ray_tracing_r_1_1_directional_light_buffer.html", null ],
        [ "MeshDescBuffer", "struct_spices_1_1_ray_tracing_r_1_1_mesh_desc_buffer.html", null ],
        [ "PointLightBuffer", "struct_spices_1_1_ray_tracing_r_1_1_point_light_buffer.html", null ],
        [ "PushConstant", "struct_spices_1_1_ray_tracing_r_1_1_push_constant.html", null ]
      ] ],
      [ "SceneCR", null, [
        [ "LightsBuffer", "struct_spices_1_1_scene_c_r_1_1_lights_buffer.html", null ]
      ] ],
      [ "ShadowR", null, [
        [ "DirectionalLightMatrixs", "struct_spices_1_1_shadow_r_1_1_directional_light_matrixs.html", null ]
      ] ],
      [ "Application", "class_spices_1_1_application.html", "class_spices_1_1_application" ],
      [ "BasePassRenderer", "class_spices_1_1_base_pass_renderer.html", "class_spices_1_1_base_pass_renderer" ],
      [ "BoxPack", "class_spices_1_1_box_pack.html", "class_spices_1_1_box_pack" ],
      [ "Camera", "class_spices_1_1_camera.html", "class_spices_1_1_camera" ],
      [ "CameraComponent", "class_spices_1_1_camera_component.html", "class_spices_1_1_camera_component" ],
      [ "CameraController", "class_spices_1_1_camera_controller.html", "class_spices_1_1_camera_controller" ],
      [ "ClassLibrary", "class_spices_1_1_class_library.html", null ],
      [ "Component", "class_spices_1_1_component.html", "class_spices_1_1_component" ],
      [ "Console", "class_spices_1_1_console.html", "class_spices_1_1_console" ],
      [ "ConstantParam", "struct_spices_1_1_constant_param.html", "struct_spices_1_1_constant_param" ],
      [ "ContainerLibrary", "class_spices_1_1_container_library.html", null ],
      [ "DescriptorSetManager", "class_spices_1_1_descriptor_set_manager.html", null ],
      [ "DirectionalLightComponent", "class_spices_1_1_directional_light_component.html", "class_spices_1_1_directional_light_component" ],
      [ "EditorWorld", "class_spices_1_1_editor_world.html", "class_spices_1_1_editor_world" ],
      [ "Entity", "class_spices_1_1_entity.html", "class_spices_1_1_entity" ],
      [ "Event", "class_spices_1_1_event.html", "class_spices_1_1_event" ],
      [ "EventDispatcher", "class_spices_1_1_event_dispatcher.html", "class_spices_1_1_event_dispatcher" ],
      [ "FileHandle", "struct_spices_1_1_file_handle.html", "struct_spices_1_1_file_handle" ],
      [ "FileLibrary", "class_spices_1_1_file_library.html", null ],
      [ "FilePack", "class_spices_1_1_file_pack.html", "class_spices_1_1_file_pack" ],
      [ "FrameInfo", "class_spices_1_1_frame_info.html", "class_spices_1_1_frame_info" ],
      [ "GBufferID", "struct_spices_1_1_g_buffer_i_d.html", "struct_spices_1_1_g_buffer_i_d" ],
      [ "ImguiAbout", "class_spices_1_1_imgui_about.html", "class_spices_1_1_imgui_about" ],
      [ "ImguiConsole", "class_spices_1_1_imgui_console.html", "class_spices_1_1_imgui_console" ],
      [ "ImguiContentBrowser", "class_spices_1_1_imgui_content_browser.html", "class_spices_1_1_imgui_content_browser" ],
      [ "ImguiCreateEntity", "class_spices_1_1_imgui_create_entity.html", "class_spices_1_1_imgui_create_entity" ],
      [ "ImguiEdit", "class_spices_1_1_imgui_edit.html", "class_spices_1_1_imgui_edit" ],
      [ "ImguiFile", "class_spices_1_1_imgui_file.html", "class_spices_1_1_imgui_file" ],
      [ "ImguiFloattingInfo", "class_spices_1_1_imgui_floatting_info.html", "class_spices_1_1_imgui_floatting_info" ],
      [ "ImguiGBufferVisualizer", "class_spices_1_1_imgui_g_buffer_visualizer.html", "class_spices_1_1_imgui_g_buffer_visualizer" ],
      [ "ImguiGizmos", "class_spices_1_1_imgui_gizmos.html", "class_spices_1_1_imgui_gizmos" ],
      [ "ImGuiH", "class_spices_1_1_im_gui_h.html", null ],
      [ "ImguiHelp", "class_spices_1_1_imgui_help.html", "class_spices_1_1_imgui_help" ],
      [ "ImguiInfoBar", "class_spices_1_1_imgui_info_bar.html", "class_spices_1_1_imgui_info_bar" ],
      [ "ImguiMainMenu", "class_spices_1_1_imgui_main_menu.html", "class_spices_1_1_imgui_main_menu" ],
      [ "ImguiMaterialPanel", "class_spices_1_1_imgui_material_panel.html", "class_spices_1_1_imgui_material_panel" ],
      [ "ImguiOperation", "class_spices_1_1_imgui_operation.html", "class_spices_1_1_imgui_operation" ],
      [ "ImguiProperty", "class_spices_1_1_imgui_property.html", "class_spices_1_1_imgui_property" ],
      [ "ImguiSlate", "class_spices_1_1_imgui_slate.html", "class_spices_1_1_imgui_slate" ],
      [ "ImguiStage", "class_spices_1_1_imgui_stage.html", "class_spices_1_1_imgui_stage" ],
      [ "ImguiUtilities", "class_spices_1_1_imgui_utilities.html", "class_spices_1_1_imgui_utilities" ],
      [ "ImguiViewport", "class_spices_1_1_imgui_viewport.html", "class_spices_1_1_imgui_viewport" ],
      [ "ImguiViewportMenu", "class_spices_1_1_imgui_viewport_menu.html", "class_spices_1_1_imgui_viewport_menu" ],
      [ "ImguiViewportToolBar", "class_spices_1_1_imgui_viewport_tool_bar.html", "class_spices_1_1_imgui_viewport_tool_bar" ],
      [ "ImguiVisualizer", "class_spices_1_1_imgui_visualizer.html", "class_spices_1_1_imgui_visualizer" ],
      [ "ImguiWindow", "class_spices_1_1_imgui_window.html", "class_spices_1_1_imgui_window" ],
      [ "InfoData", "struct_spices_1_1_info_data.html", "struct_spices_1_1_info_data" ],
      [ "InfoLevelHelper", "struct_spices_1_1_info_level_helper.html", null ],
      [ "Input", "class_spices_1_1_input.html", "class_spices_1_1_input" ],
      [ "KeyEvent", "class_spices_1_1_key_event.html", "class_spices_1_1_key_event" ],
      [ "KeyPressedEvent", "class_spices_1_1_key_pressed_event.html", "class_spices_1_1_key_pressed_event" ],
      [ "KeyReleasedEvent", "class_spices_1_1_key_released_event.html", "class_spices_1_1_key_released_event" ],
      [ "KeyTypedEvent", "class_spices_1_1_key_typed_event.html", "class_spices_1_1_key_typed_event" ],
      [ "Log", "class_spices_1_1_log.html", null ],
      [ "Material", "class_spices_1_1_material.html", "class_spices_1_1_material" ],
      [ "MaterialLoader", "class_spices_1_1_material_loader.html", null ],
      [ "MemoryLibrary", "class_spices_1_1_memory_library.html", null ],
      [ "Mesh", "class_spices_1_1_mesh.html", "class_spices_1_1_mesh" ],
      [ "MeshAddedWorldEvent", "class_spices_1_1_mesh_added_world_event.html", "class_spices_1_1_mesh_added_world_event" ],
      [ "MeshComponent", "class_spices_1_1_mesh_component.html", "class_spices_1_1_mesh_component" ],
      [ "MeshController", "class_spices_1_1_mesh_controller.html", "class_spices_1_1_mesh_controller" ],
      [ "MeshLoader", "class_spices_1_1_mesh_loader.html", null ],
      [ "MeshPack", "class_spices_1_1_mesh_pack.html", "class_spices_1_1_mesh_pack" ],
      [ "MouseButtonEvent", "class_spices_1_1_mouse_button_event.html", "class_spices_1_1_mouse_button_event" ],
      [ "MouseButtonPressedEvent", "class_spices_1_1_mouse_button_pressed_event.html", "class_spices_1_1_mouse_button_pressed_event" ],
      [ "MouseButtonReleasedEvent", "class_spices_1_1_mouse_button_released_event.html", "class_spices_1_1_mouse_button_released_event" ],
      [ "MouseMovedEvent", "class_spices_1_1_mouse_moved_event.html", "class_spices_1_1_mouse_moved_event" ],
      [ "MouseScrolledEvent", "class_spices_1_1_mouse_scrolled_event.html", "class_spices_1_1_mouse_scrolled_event" ],
      [ "NativeScript", "class_spices_1_1_native_script.html", "class_spices_1_1_native_script" ],
      [ "NativeScriptComponent", "class_spices_1_1_native_script_component.html", "class_spices_1_1_native_script_component" ],
      [ "NativeScriptRegister", "class_spices_1_1_native_script_register.html", "class_spices_1_1_native_script_register" ],
      [ "NativeScriptSystem", "class_spices_1_1_native_script_system.html", "class_spices_1_1_native_script_system" ],
      [ "OrthographicParam", "struct_spices_1_1_orthographic_param.html", null ],
      [ "PerspectiveParam", "struct_spices_1_1_perspective_param.html", null ],
      [ "PipelineConfigInfo", "struct_spices_1_1_pipeline_config_info.html", "struct_spices_1_1_pipeline_config_info" ],
      [ "PointLightComponent", "class_spices_1_1_point_light_component.html", "class_spices_1_1_point_light_component" ],
      [ "PreRenderer", "class_spices_1_1_pre_renderer.html", "class_spices_1_1_pre_renderer" ],
      [ "ProcessLibrary", "class_spices_1_1_process_library.html", null ],
      [ "QueueHelper", "struct_spices_1_1_queue_helper.html", "struct_spices_1_1_queue_helper" ],
      [ "RayTracingComposeRenderer", "class_spices_1_1_ray_tracing_compose_renderer.html", "class_spices_1_1_ray_tracing_compose_renderer" ],
      [ "RayTracingRenderer", "class_spices_1_1_ray_tracing_renderer.html", "class_spices_1_1_ray_tracing_renderer" ],
      [ "Renderer", "class_spices_1_1_renderer.html", "class_spices_1_1_renderer" ],
      [ "RendererManager", "class_spices_1_1_renderer_manager.html", "class_spices_1_1_renderer_manager" ],
      [ "RendererPass", "class_spices_1_1_renderer_pass.html", null ],
      [ "RendererResource", "class_spices_1_1_renderer_resource.html", "class_spices_1_1_renderer_resource" ],
      [ "RendererResourceCreateInfo", "struct_spices_1_1_renderer_resource_create_info.html", "struct_spices_1_1_renderer_resource_create_info" ],
      [ "RendererResourcePool", "class_spices_1_1_renderer_resource_pool.html", "class_spices_1_1_renderer_resource_pool" ],
      [ "RendererSubPass", "class_spices_1_1_renderer_sub_pass.html", "class_spices_1_1_renderer_sub_pass" ],
      [ "RenderFrontend", "class_spices_1_1_render_frontend.html", null ],
      [ "RenderSystem", "class_spices_1_1_render_system.html", "class_spices_1_1_render_system" ],
      [ "ResourcePool", "class_spices_1_1_resource_pool.html", "class_spices_1_1_resource_pool" ],
      [ "ResourceSystem", "class_spices_1_1_resource_system.html", "class_spices_1_1_resource_system" ],
      [ "RuntimeWorld", "class_spices_1_1_runtime_world.html", "class_spices_1_1_runtime_world" ],
      [ "SceneComposeRenderer", "class_spices_1_1_scene_compose_renderer.html", "class_spices_1_1_scene_compose_renderer" ],
      [ "ShadowRenderer", "class_spices_1_1_shadow_renderer.html", "class_spices_1_1_shadow_renderer" ],
      [ "SkyBoxComponent", "class_spices_1_1_sky_box_component.html", "class_spices_1_1_sky_box_component" ],
      [ "SlateRegister", "class_spices_1_1_slate_register.html", "class_spices_1_1_slate_register" ],
      [ "SlateRenderer", "class_spices_1_1_slate_renderer.html", "class_spices_1_1_slate_renderer" ],
      [ "SlateResizeEvent", "class_spices_1_1_slate_resize_event.html", "class_spices_1_1_slate_resize_event" ],
      [ "SlateSystem", "class_spices_1_1_slate_system.html", "class_spices_1_1_slate_system" ],
      [ "SpherePack", "class_spices_1_1_sphere_pack.html", "class_spices_1_1_sphere_pack" ],
      [ "SpriteComponent", "class_spices_1_1_sprite_component.html", "class_spices_1_1_sprite_component" ],
      [ "SpriteRenderer", "class_spices_1_1_sprite_renderer.html", "class_spices_1_1_sprite_renderer" ],
      [ "SquarePack", "class_spices_1_1_square_pack.html", "class_spices_1_1_square_pack" ],
      [ "String2", "struct_spices_1_1_string2.html", null ],
      [ "StringLibrary", "class_spices_1_1_string_library.html", null ],
      [ "SwapChainSupportDetails", "struct_spices_1_1_swap_chain_support_details.html", "struct_spices_1_1_swap_chain_support_details" ],
      [ "System", "class_spices_1_1_system.html", "class_spices_1_1_system" ],
      [ "SystemManager", "class_spices_1_1_system_manager.html", "class_spices_1_1_system_manager" ],
      [ "TagComponent", "class_spices_1_1_tag_component.html", "class_spices_1_1_tag_component" ],
      [ "TestRenderer", "class_spices_1_1_test_renderer.html", "class_spices_1_1_test_renderer" ],
      [ "Texture", "class_spices_1_1_texture.html", "class_spices_1_1_texture" ],
      [ "Texture2D", "class_spices_1_1_texture2_d.html", "class_spices_1_1_texture2_d" ],
      [ "Texture2DArray", "class_spices_1_1_texture2_d_array.html", "class_spices_1_1_texture2_d_array" ],
      [ "Texture2DCube", "class_spices_1_1_texture2_d_cube.html", "class_spices_1_1_texture2_d_cube" ],
      [ "TextureLoader", "class_spices_1_1_texture_loader.html", null ],
      [ "TextureParam", "struct_spices_1_1_texture_param.html", "struct_spices_1_1_texture_param" ],
      [ "TimeStep", "class_spices_1_1_time_step.html", "class_spices_1_1_time_step" ],
      [ "TransformComponent", "class_spices_1_1_transform_component.html", "class_spices_1_1_transform_component" ],
      [ "UInt2", "struct_spices_1_1_u_int2.html", null ],
      [ "UUID", "class_spices_1_1_u_u_i_d.html", null ],
      [ "UUIDComponent", "class_spices_1_1_u_u_i_d_component.html", "class_spices_1_1_u_u_i_d_component" ],
      [ "Vertex", "struct_spices_1_1_vertex.html", "struct_spices_1_1_vertex" ],
      [ "ViewPortResizeQueryer", "class_spices_1_1_view_port_resize_queryer.html", "class_spices_1_1_view_port_resize_queryer" ],
      [ "VulkanBuffer", "class_spices_1_1_vulkan_buffer.html", "class_spices_1_1_vulkan_buffer" ],
      [ "VulkanCommandBuffer", "class_spices_1_1_vulkan_command_buffer.html", "class_spices_1_1_vulkan_command_buffer" ],
      [ "VulkanCommandPool", "class_spices_1_1_vulkan_command_pool.html", "class_spices_1_1_vulkan_command_pool" ],
      [ "VulkanDebugUtils", "class_spices_1_1_vulkan_debug_utils.html", null ],
      [ "VulkanDescriptorPool", "class_spices_1_1_vulkan_descriptor_pool.html", "class_spices_1_1_vulkan_descriptor_pool" ],
      [ "VulkanDescriptorSet", "class_spices_1_1_vulkan_descriptor_set.html", "class_spices_1_1_vulkan_descriptor_set" ],
      [ "VulkanDescriptorSetLayout", "class_spices_1_1_vulkan_descriptor_set_layout.html", "class_spices_1_1_vulkan_descriptor_set_layout" ],
      [ "VulkanDevice", "class_spices_1_1_vulkan_device.html", "class_spices_1_1_vulkan_device" ],
      [ "VulkanImage", "class_spices_1_1_vulkan_image.html", "class_spices_1_1_vulkan_image" ],
      [ "VulkanInstance", "class_spices_1_1_vulkan_instance.html", "class_spices_1_1_vulkan_instance" ],
      [ "VulkanObject", "class_spices_1_1_vulkan_object.html", "class_spices_1_1_vulkan_object" ],
      [ "VulkanPipeline", "class_spices_1_1_vulkan_pipeline.html", "class_spices_1_1_vulkan_pipeline" ],
      [ "VulkanRayTracing", "class_spices_1_1_vulkan_ray_tracing.html", "class_spices_1_1_vulkan_ray_tracing" ],
      [ "VulkanRayTracingPipeline", "class_spices_1_1_vulkan_ray_tracing_pipeline.html", "class_spices_1_1_vulkan_ray_tracing_pipeline" ],
      [ "VulkanRenderBackend", "class_spices_1_1_vulkan_render_backend.html", "class_spices_1_1_vulkan_render_backend" ],
      [ "VulkanRenderPass", "class_spices_1_1_vulkan_render_pass.html", "class_spices_1_1_vulkan_render_pass" ],
      [ "VulkanShaderModule", "class_spices_1_1_vulkan_shader_module.html", "class_spices_1_1_vulkan_shader_module" ],
      [ "VulkanState", "struct_spices_1_1_vulkan_state.html", "struct_spices_1_1_vulkan_state" ],
      [ "VulkanSwapChain", "class_spices_1_1_vulkan_swap_chain.html", "class_spices_1_1_vulkan_swap_chain" ],
      [ "VulkanWindows", "class_spices_1_1_vulkan_windows.html", "class_spices_1_1_vulkan_windows" ],
      [ "WindowCloseEvent", "class_spices_1_1_window_close_event.html", "class_spices_1_1_window_close_event" ],
      [ "WindowIcon", "struct_spices_1_1_window_icon.html", "struct_spices_1_1_window_icon" ],
      [ "WindowInfo", "struct_spices_1_1_window_info.html", "struct_spices_1_1_window_info" ],
      [ "WindowResizeEvent", "class_spices_1_1_window_resize_event.html", "class_spices_1_1_window_resize_event" ],
      [ "WindowResizeOverEvent", "class_spices_1_1_window_resize_over_event.html", "class_spices_1_1_window_resize_over_event" ],
      [ "WindowsInput", "class_spices_1_1_windows_input.html", "class_spices_1_1_windows_input" ],
      [ "World", "class_spices_1_1_world.html", "class_spices_1_1_world" ],
      [ "WorldEvent", "class_spices_1_1_world_event.html", "class_spices_1_1_world_event" ],
      [ "WorldMarkQueryer", "class_spices_1_1_world_mark_queryer.html", "class_spices_1_1_world_mark_queryer" ],
      [ "WorldPickIDQueryer", "class_spices_1_1_world_pick_i_d_queryer.html", "class_spices_1_1_world_pick_i_d_queryer" ],
      [ "WorldPickRenderer", "class_spices_1_1_world_pick_renderer.html", "class_spices_1_1_world_pick_renderer" ],
      [ "WorldPickStage2Renderer", "class_spices_1_1_world_pick_stage2_renderer.html", "class_spices_1_1_world_pick_stage2_renderer" ]
    ] ],
    [ "std", null, [
      [ "hash< Spices::String2 >", "structstd_1_1hash_3_01_spices_1_1_string2_01_4.html", null ],
      [ "hash< Spices::UInt2 >", "structstd_1_1hash_3_01_spices_1_1_u_int2_01_4.html", null ],
      [ "hash< Spices::UUID >", "structstd_1_1hash_3_01_spices_1_1_u_u_i_d_01_4.html", null ],
      [ "hash< Spices::Vertex >", "structstd_1_1hash_3_01_spices_1_1_vertex_01_4.html", null ]
    ] ],
    [ "YAML", null, [
      [ "convert< glm::vec2 >", "struct_y_a_m_l_1_1convert_3_01glm_1_1vec2_01_4.html", null ],
      [ "convert< glm::vec3 >", "struct_y_a_m_l_1_1convert_3_01glm_1_1vec3_01_4.html", null ],
      [ "convert< glm::vec4 >", "struct_y_a_m_l_1_1convert_3_01glm_1_1vec4_01_4.html", null ],
      [ "convert< Spices::ConstantParam >", "struct_y_a_m_l_1_1convert_3_01_spices_1_1_constant_param_01_4.html", null ],
      [ "convert< Spices::TextureParam >", "struct_y_a_m_l_1_1convert_3_01_spices_1_1_texture_param_01_4.html", null ]
    ] ]
];